
TARGET   = lib/GLFW.a

SOURCES  = src/lib/enable.c \
           src/lib/fullscreen.c \
           src/lib/glext.c \
           src/lib/image.c \
           src/lib/init.c \
           src/lib/input.c \
           src/lib/joystick.c \
           src/lib/stream.c \
           src/lib/tga.c \
           src/lib/thread.c \
           src/lib/time.c \
           src/lib/window.c \
           src/lib/cocoa/cocoa_thread.c

OBJCSOURCES1 = src/lib/cocoa/cocoa_enable.m \
               src/lib/cocoa/cocoa_fullscreen.m \
               src/lib/cocoa/cocoa_glext.m \
               src/lib/cocoa/cocoa_joystick.m \
               src/lib/cocoa/cocoa_time.m

OBJCSOURCES2 = src/lib/cocoa/cocoa_init.m \
               src/lib/cocoa/cocoa_window.m

OBJECTS  = $(SOURCES:.c=.o) $(OBJCSOURCES1:.m=.o) $(OBJCSOURCES2:.m=.o)

CXX      = gcc
AR       = ar
CXXFLAGS = -Wall -O6 -fomit-frame-pointer \
           -fno-common \
           -DMMDAGENT
INCLUDE  = -I src/include \
           -I src/lib \
           -I src/lib/cocoa

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(AR) cru $(TARGET) $(OBJECTS)
	$(AR) cru lib/GLFW_part.a $(SOURCES:.c=.o) $(OBJCSOURCES1:.m=.o)
	cp src/include/GL/glfw.h include/GL/glfw.h

.c.o:
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o $(<:.c=.o) -c $<

.m.o:
	$(CXX) $(CXXFLAGS) $(INCLUDE) -o $(<:.m=.o) -c $<

clean:
	rm -f $(OBJECTS) $(TARGET)
